[package]
name = "fetching"
version = "1.0.4"
edition = "2021"

[[bin]]
name = "fetching"
path = "main.rs"

[dependencies]
anyhow = "1"
tracing = "0.1"
tracing-subscriber = "0.3"
tokio = { version = "1", features = ["full"] }
librespot-core = "0.8.0"
axum = "0.7"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
uuid = { version = "1", features = ["v4"] }
futures-util = "0.3.32"
async-stream = "0.3.6"

fetching-core = { path = "core" }
server = { path = "server" }
clap = { version = "4.5.58", features = ["derive"] }

[workspace]
resolver = "2"
members = ["core", "server"]
