[package]
name = "fetching-core"
version = "0.1.17"
edition = "2024"

[[bin]]
name = "test"
path = "src/main.rs"


[lib]
name = "fetching_core_lib"
path = "src/lib.rs"

[dependencies]
librespot-core = "0.8.0"
librespot-metadata = "0.8.0"
librespot-audio = "0.8.0"
librespot-oauth = "0.8.0"
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.149"
futures = "0.3.32"
hex = "0.4.3"
clap = { version = "4.5.60", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
tracing = "0.1.44"
tempfile = "3.25.0"
reqwest = "0.13.2"
tokio-fs = "0.1.7"
async-trait = "0.1.89"
moka = { version = "0.12.13", features = ["future"]}
uuid = { version = "1", features = ["v4", "serde"] }
chrono = "0.4.44"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }


[dev-dependencies]
pretty_assertions = "1"
